DROP TABLE IF EXISTS works_in;
DROP TABLE IF EXISTS responsible;
DROP TABLE IF EXISTS deposit;
DROP TABLE IF EXISTS worker;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS interest_rate;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS bank;
